### ISSUE TITLE
Adjust to accomodate participant gender for event?

### ISSUE THREAD

**Issue by magnolia61** [veda-consulting/uk.co.vedaconsulting.multipleparticipantroleforevent#1]
Hi Parvez,
Would it be difficult to modify this extension to make it possible to have a different registration link for male of female participants. We organise summercamps and many times an event is full, but only for boys.
Would this extension be a good starter or would you think this is better handled in core, to make it possible to configure seperate maximums and have a separate waitlist for boys of girls?
I'm asking you because you seem to be very involved into the whole event resgistration part of civicrm :-)

With kind regards, Richard van Oosterhout (The Netherlands)

**Comment by priyankakaran26** [comment]
Hi Richard,

Thanks for contacting us!

-- To have different registration links for male or female participants, you can simply create two different participant roles to say Summer Camp Boys/Summer Camp Girls. The extension would automatically generate different registration URLs for both of them and these links would then be accessible under "Info and Settings" tab on Event Configuration page.
-- I think it would be better to have that functionality in an extension.

Hope this helps!

Thanks,
Priyanka
