### ISSUE TITLE
Profile specific for different contact subtypes

### ISSUE THREAD

**Issue by magnolia61** [veda-consulting/uk.co.vedaconsulting.multipleparticipantroleforevent#3]
Hi there,
I don't know if this extension is still in use with you or alive at all, but I wanted to check if is somehow possible to show different profiles in the registration form for different participant roles.

For example: It would make sense to ask camp leaders different questions during registration than the camp kids. Or a workshop speaker different questions than the workshop visitors.

Would this be possible?

**Comment by veda-consulting** [comment]
@magnolia61, sorry for the very late reply. Yes the extension is still used. You can determine which custom data should be shown for which role which in turn could be based on the contact subtype. So its not part of the extension as such but could be achieved.
